# Generated by Django 3.2.11 on 2022-01-23 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('total_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('stop_no', models.PositiveIntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='bookings.station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='bookings.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.train')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('pnr', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_journey', models.DateTimeField()),
                ('number_of_seats', models.PositiveIntegerField()),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_station', to='bookings.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_station', to='bookings.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.train')),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available_seats', models.PositiveIntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.train')),
            ],
        ),
        migrations.AddConstraint(
            model_name='route',
            constraint=models.UniqueConstraint(fields=('train', 'source', 'destination', 'arrival_time'), name='unique_route_train'),
        ),
        migrations.AddConstraint(
            model_name='availability',
            constraint=models.UniqueConstraint(fields=('train', 'station', 'date'), name='unique_availability'),
        ),
    ]
