# Generated by Django 4.0.1 on 2022-01-23 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_seats', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_no', models.PositiveIntegerField()),
                ('available_seats', models.PositiveIntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_booking.bookingss.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_booking.bookingss.train')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_stops', models.PositiveIntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='train_booking.bookingss.station')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='train_booking.bookingss.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_booking.bookingss.train')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_seats', models.PositiveIntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_booking.bookingss.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_booking.bookingss.train')),
            ],
        ),
        migrations.CreateModel(
            name='train_booking.bookings',
            fields=[
                ('pnr', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_journey', models.DateTimeField()),
                ('number_of_seats', models.PositiveIntegerField()),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_station', to='train_booking.bookingss.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_station', to='train_booking.bookingss.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train_booking.bookingss.train')),
            ],
        ),
    ]
