# Generated by Django 3.2.11 on 2022-01-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='stop_no',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
