# Generated by Django 3.2.11 on 2022-01-24 20:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_route_stop_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.PositiveIntegerField(db_index=True)),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.train')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='train_charting_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='stop_no',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.CreateModel(
            name='SeatAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.seat')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.station')),
            ],
        ),
    ]
