# Generated by Django 3.2.11 on 2022-01-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20220124_2015'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seat',
            constraint=models.UniqueConstraint(fields=('train', 'seat_no'), name='unique_train_seat'),
        ),
        migrations.AddConstraint(
            model_name='seatavailability',
            constraint=models.UniqueConstraint(fields=('station', 'seat', 'date'), name='unique_train_seat_station_for_date'),
        ),
    ]
